export type Chunk={id:string;level:"A1"|"A2"|"B1"|"B2";text:string;meaning:string;pattern:string;register:string;usage:string;grammar:string;pronunciation:string;skills:string[];audio?:{natural?:string;slow?:string;voice:string}};
export const chunks:Chunk[]=[
{id:"a1-nice-to-meet-you",level:"A1",text:"Nice to meet you.",meaning:"Prazer em conhecer você.",pattern:"Nice to meet you",register:"neutro",usage:"Primeiro encontro ou apresentação.",grammar:"O bloco inteiro funciona como uma resposta social pronta.",pronunciation:"nice tə meetcha",skills:["social","listening"]},
{id:"a1-how-is-it-going",level:"A1",text:"How's it going?",meaning:"Como vão as coisas?",pattern:"How's it going?",register:"conversacional",usage:"Cumprimento informal muito frequente.",grammar:"How is contrai para How’s. Não é uma pergunta sobre movimento.",pronunciation:"howzit going",skills:["social","connected-speech"]},
{id:"a1-not-really",level:"A1",text:"Not really.",meaning:"Na verdade, não muito.",pattern:"Not really",register:"conversacional",usage:"Negativa suave em conversas.",grammar:"Resposta curta que evita repetir a pergunta inteira.",pronunciation:"not really",skills:["interaction"]},
{id:"a2-im-up-for-it",level:"A2",text:"I'm up for it.",meaning:"Eu topo / estou disposto.",pattern:"be up for + coisa",register:"informal",usage:"Aceitar convite ou atividade.",grammar:"Depois de for, use substantivo ou verbo com -ing: I’m up for trying it.",pronunciation:"aim up fər it",skills:["interaction","vocabulary"]},
{id:"a2-figure-it-out",level:"A2",text:"We'll figure it out.",meaning:"Vamos dar um jeito / descobrir a solução.",pattern:"figure something out",register:"conversacional",usage:"Encorajamento diante de um problema.",grammar:"Phrasal verb separável: figure it out, nunca figure out it.",pronunciation:"we'll figyer it out",skills:["phrasal-verbs","speaking"]},
{id:"a2-no-big-deal",level:"A2",text:"It's no big deal.",meaning:"Não é nada demais.",pattern:"no big deal",register:"informal",usage:"Minimizar um problema ou favor.",grammar:"Deal aqui não significa negócio; o chunk inteiro expressa pouca importância.",pronunciation:"sno big deal",skills:["interaction","listening"]},
{id:"b1-didnt-mean-to",level:"B1",text:"I didn't mean to upset you.",meaning:"Eu não queria magoar você.",pattern:"I didn't mean to + verbo",register:"neutro",usage:"Explicar uma consequência não intencional.",grammar:"Após mean to, use o verbo na forma base.",pronunciation:"I didn mean tə upsetcha",skills:["repair","connected-speech"]},
{id:"b1-get-around-to",level:"B1",text:"I haven't got around to it yet.",meaning:"Ainda não consegui arrumar tempo para isso.",pattern:"get around to + nome/-ing",register:"conversacional",usage:"Tarefa ainda não realizada por falta de oportunidade.",grammar:"To é preposição; com verbo, use -ing: got around to calling.",pronunciation:"I haven got around tə it yet",skills:["phrasal-verbs","present-perfect"]},
{id:"b1-that-makes-sense",level:"B1",text:"That makes sense.",meaning:"Isso faz sentido.",pattern:"make sense",register:"neutro",usage:"Mostrar que compreendeu uma explicação.",grammar:"Sense aparece sem artigo neste chunk.",pronunciation:"that makes sense",skills:["interaction"]},
{id:"b2-fair-point",level:"B2",text:"That's a fair point, but…",meaning:"Esse é um ponto válido, mas…",pattern:"That's a fair point",register:"neutro",usage:"Discordar sem ignorar o argumento do outro.",grammar:"But introduz o contraste; a pausa ajuda a manter o tom diplomático.",pronunciation:"that's a fair point, but",skills:["argumentation","pragmatics"]},
{id:"b2-take-step-back",level:"B2",text:"Let's take a step back.",meaning:"Vamos recuar um pouco e rever a situação.",pattern:"take a step back",register:"profissional",usage:"Reavaliar uma discussão ou decisão.",grammar:"Let’s + verbo base propõe uma ação conjunta.",pronunciation:"let's take a step back",skills:["professional","interaction"]},
{id:"b2-not-entirely-convinced",level:"B2",text:"I'm not entirely convinced.",meaning:"Não estou totalmente convencido.",pattern:"not entirely + adjetivo",register:"neutro/formal",usage:"Discordância cautelosa e diplomática.",grammar:"Not entirely suaviza a discordância.",pronunciation:"I'm not entirely convinced",skills:["hedging","argumentation"]},
];
